<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:10mm}body{font-family:DejaVu Sans,sans-serif;font-size:8px;color:#111}h1{text-align:center;font-size:15px;margin:0 0 10px}.meta{display:flex;justify-content:space-between;margin-bottom:10px}.family{page-break-inside:avoid;margin-bottom:14px}.family h2{font-size:10px;margin:0;padding:5px;background:#ffff00;border:1px solid #111}table{width:100%;border-collapse:collapse}th,td{border:1px solid #111;padding:4px;text-align:center}th{background:#ffff00;font-size:7px}.footer{margin-top:16px;text-align:center;font-size:7px}
</style></head><body>
<h1>HOUSEHOLD RECORD OF BARANGAY INHABITANTS (RBI)</h1>
<div class="meta"><span>Region: <b>VIII</b> · Province: <b>SOUTHERN LEYTE</b> · Municipality: <b>TOMAS OPPUS</b></span><span>Barangay: <b>{{ strtoupper($barangay->name) }}</b> · Reporting Month: <b>{{ strtoupper(date('F Y', strtotime($month.'-01'))) }}</b></span></div>
@foreach($families as $household => $members)<section class="family"><h2>FAMILY / HOUSEHOLD NO. {{ $household }}</h2><table><thead><tr><th>LAST</th><th>FIRST</th><th>MIDDLE</th><th>Qualifier</th><th>RELATIONSHIP</th><th>ADDRESS</th><th>PLACE OF BIRTH</th><th>DATE OF BIRTH</th><th>AGE</th><th>SEX</th><th>CIVIL STATUS</th><th>SCHOOL LEVEL</th><th>RELIGION</th><th>OCCUPATION</th><th>REMARKS</th></tr></thead><tbody>
@foreach($members as $member)<tr><td>{{ $member->last_name }}</td><td>{{ $member->first_name }}</td><td>{{ $member->middle_name }}</td><td>{{ $member->suffix }}</td><td>{{ $member->relationship_to_head }}</td><td>{{ $member->complete_address }}</td><td>{{ $member->birth_place }}</td><td>{{ optional($member->birth_date)->format('m-d-Y') }}</td><td>{{ $member->recorded_age }}</td><td>{{ $member->sex === 'Male' ? 'M' : 'F' }}</td><td>{{ $member->civil_status }}</td><td>{{ $member->education_level }}</td><td>{{ $member->religion }}</td><td>{{ $member->occupation }}</td><td>{{ $member->remarks }}</td></tr>@endforeach
</tbody></table></section>@endforeach
<div class="footer">Prepared by: <b>NENA E. GONZAGA — BHW</b> &nbsp;&nbsp;&nbsp; Certified Correct: <b>MARY GRACE M. POLISTICO — Barangay Secretary</b> &nbsp;&nbsp;&nbsp; Verified by: <b>MARCOS L. MAQUILANG SR. — Punong Barangay</b></div>
</body></html>
