@extends('layouts.app')
@section('content')
<section class="grid min-w-0 grid-cols-1 gap-6">
    <header class="dashboard-page-header">
            <x-workspace-heading icon="activity"><span class="dashboard-eyebrow">Municipal overview</span><h1>Concern Insights</h1><p>Concerns submitted from {{ $start->format('M d, Y') }} through today, grouped by their current status and staff-reviewed category where available.</p></x-workspace-heading></header>
    @include('concerns._feedback')
    <form method="GET" action="{{ route('concerns.summary') }}" class="flex flex-wrap items-end gap-3 rounded-xl border border-slate-200 bg-white p-4"><div><label for="area">Barangay</label><select id="area" name="barangay_id"><option value="">All barangays</option>@foreach($barangays as $area)<option value="{{ $area->id }}" @selected((string) request('barangay_id') === (string) $area->id)>{{ $area->name }}</option>@endforeach</select></div><div><label for="days">Submission window</label><select id="days" name="days">@foreach([30,90,365] as $period)<option value="{{ $period }}" @selected($days === $period)>Last {{ $period }} days</option>@endforeach</select></div><button type="submit">Apply filters</button></form>
    <div class="grid gap-4 md:grid-cols-3">@foreach([['Submitted in this window', $rows->sum('total')], ['Still open', $rows->whereIn('status', ['submitted','under_review','in_progress'])->sum('total')], ['Marked resolved', $rows->where('status','resolved')->sum('total')]] as [$label,$count])<article class="rounded-xl border border-slate-200 bg-white p-5"><h2>{{ $label }}</h2><strong class="mt-3 block text-3xl">{{ number_format($count) }}</strong></article>@endforeach</div>
    <p class="rounded-xl border border-slate-200 bg-white p-4 text-sm text-slate-600">These are submitted concern counts, not verified incident rates or resident risk scores. Closed is separate from resolved. Low counts can reflect limited participation. Individual descriptions, identities, and attachments are restricted to the resident and assigned barangay.</p>
    <div class="grid gap-6 lg:grid-cols-2">
        <article class="rounded-xl border border-slate-200 bg-white p-5"><h2>Concern categories</h2><div class="mt-5 grid gap-4">@foreach(\App\Models\ResidentConcern::categories() as $key => $label)@php($count = $rows->where('category',$key)->sum('total'))<div><div class="mb-2 flex justify-between gap-3 text-sm"><span>{{ $label }}</span><strong>{{ number_format($count) }}</strong></div><div class="h-2 overflow-hidden rounded-full bg-slate-100" aria-hidden="true"><div class="h-2 rounded-full bg-blue-700" style="width: {{ round(100 * $count / max(1, $rows->sum('total')), 1) }}%"></div></div></div>@endforeach</div></article>
        <article class="rounded-xl border border-slate-200 bg-white p-5"><h2>Current status</h2><dl class="mt-5 grid gap-4">@foreach(\App\Models\ResidentConcern::statuses() as $key => $label)<div class="flex justify-between gap-3 border-b border-slate-100 pb-3"><dt>{{ $label }}</dt><dd class="font-semibold">{{ number_format($rows->where('status',$key)->sum('total')) }}</dd></div>@endforeach</dl></article>
    </div>
    <div class="table-wrap"><table><thead><tr><th scope="col">Barangay</th><th scope="col">Submitted</th><th scope="col">Still open</th><th scope="col">Resolved</th><th scope="col">Closed</th></tr></thead><tbody>
        @foreach($barangays->filter(fn ($area) => !request('barangay_id') || (int) request('barangay_id') === $area->id) as $area)@php($group = $rows->where('barangay_id',$area->id))<tr><th scope="row">{{ $area->name }}</th><td>{{ $group->sum('total') }}</td><td>{{ $group->whereIn('status',['submitted','under_review','in_progress'])->sum('total') }}</td><td>{{ $group->where('status','resolved')->sum('total') }}</td><td>{{ $group->where('status','closed')->sum('total') }}</td></tr>@endforeach
    </tbody></table></div>
</section>
@endsection
